import type { AssistanceRequest, Confirmation, Facility, RequestEvent } from '../domain/contracts';
export type ProviderKind = 'person' | 'organization' | 'community_center';
// Visual fixture wrapper. Persisted providerType confirmed by backend PROVIDER-TYPES; kind is presentation only.
export interface PreviewProvider { facility: Facility; kind: ProviderKind; service: string; summary: string; initials: string; color: string; confirmation?: Confirmation; operational: string; resources: string; electricity: string; generator: string }
export const kindText: Record<ProviderKind, string> = { person: 'Persona', organization: 'Organización', community_center: 'Centro comunitario' };
export const municipalities = ['Adjuntas', 'Ponce', 'San Juan'];
const confirmation: Confirmation = { source: 'FacilityConfirmed', confirmedAt: '2026-10-09T12:07:29.115Z', validUntil: '2026-10-10T12:07:29.115Z' };
export const providers: PreviewProvider[] = [
  { facility: { $id: 'hackathon-demo-pharmacy', name: 'Farmacia comunitaria', municipalityId: '72001', address: 'Adjuntas, Puerto Rico', hours: '8:00 a. m. – 6:00 p. m.', teamId: 'hackathon-demo-team' }, kind: 'organization', service: 'Medicamentos', summary: 'Orientación sobre disponibilidad reportada de medicamentos y artículos esenciales.', initials: '+', color: 'teal', confirmation, operational: 'Operativo', resources: 'Disponibilidad limitada · no es inventario verificado', electricity: 'Disponible', generator: 'Disponible' },
  { facility: { $id: 'preview-luz', name: 'Luz Méndez', municipalityId: '72001', address: 'Adjuntas, Puerto Rico', hours: '9:00 a. m. – 3:00 p. m.', teamId: 'preview' }, kind: 'person', service: 'Alimentos', summary: 'Apoyo comunitario con alimentos y artículos de primera necesidad.', initials: 'LM', color: 'peach', confirmation: { ...confirmation, source: 'CommunityReported' }, operational: 'Estado reportado', resources: 'Consultar directamente con la persona', electricity: 'Sin información', generator: 'No aplica' },
  { facility: { $id: 'preview-puente', name: 'Centro El Puente', municipalityId: '72001', address: 'Adjuntas, Puerto Rico', hours: '10:00 a. m. – 5:00 p. m.', teamId: 'preview' }, kind: 'community_center', service: 'Artículos esenciales', summary: 'Un punto de encuentro para orientación y apoyo a la comunidad.', initials: 'EP', color: 'lavender', confirmation: { ...confirmation, confirmedAt: '2026-10-07T12:00:00Z', validUntil: '2026-10-08T12:00:00Z' }, operational: 'Sin información operativa', resources: 'Sin información reciente', electricity: 'Sin información', generator: 'Sin información' },
];
export const sampleRequest: AssistanceRequest = { $id: 'hackathon-demo-request', citizenId: 'demo-citizen', facilityId: 'hackathon-demo-pharmacy', municipalityId: '72001', serviceId: 'pharmacy', description: 'Consulta sobre artículos esenciales disponibles.', status: 'acknowledged' };
export const sampleEvents: RequestEvent[] = [ { $id: 'preview-event-1', requestId: sampleRequest.$id, eventType: 'submitted', actorId: 'demo-citizen', occurredAt: '2026-10-09T12:10:00Z' }, { $id: 'preview-event-2', requestId: sampleRequest.$id, eventType: 'acknowledged', actorId: 'demo-provider', occurredAt: '2026-10-09T12:15:00Z', responseNote: 'Recibimos tu consulta. Verificaremos la disponibilidad y responderemos por este medio. ' } ];
